# Generated by Django 5.0.4 on 2024-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('complementos', 'complementos'), ('medida', 'medida'), ('sabor', 'sabor')], max_length=100),
        ),
    ]
