# Generated by Django 5.0.4 on 2024-05-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_county_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='addres_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='addres_line_2',
        ),
    ]
