# Generated by Django 5.0.4 on 2024-05-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_address_line_1_order_addres_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='complemento',
            new_name='complementos',
        ),
    ]
